# 1 "builtin-cproj-1.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "builtin-cproj-1.c"
# 15 "builtin-cproj-1.c"
extern void link_error(int);
# 192 "builtin-cproj-1.c"
void foo (_Complex long double cld, _Complex double cd, _Complex float cf,
   long double ld, double d, float f, int x)
{
  do { if (__builtin_cprojf(__builtin_inff()+0I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(__builtin_inff()+0I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(195); if (__builtin_cproj(__builtin_inff()+0I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(__builtin_inff()+0I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(195); if (__builtin_cprojl(__builtin_inff()+0I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(__builtin_inff()+0I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(195); } while (0);
  do { if (__builtin_cprojf(__builtin_inff()-0I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(__builtin_inff()-0I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(196); if (__builtin_cproj(__builtin_inff()-0I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(__builtin_inff()-0I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(196); if (__builtin_cprojl(__builtin_inff()-0I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(__builtin_inff()-0I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(196); } while (0);
  do { if (__builtin_cprojf(__builtin_inff()+4I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(__builtin_inff()+4I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(197); if (__builtin_cproj(__builtin_inff()+4I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(__builtin_inff()+4I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(197); if (__builtin_cprojl(__builtin_inff()+4I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(__builtin_inff()+4I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(197); } while (0);
  do { if (__builtin_cprojf(__builtin_inff()-4I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(__builtin_inff()-4I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(198); if (__builtin_cproj(__builtin_inff()-4I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(__builtin_inff()-4I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(198); if (__builtin_cprojl(__builtin_inff()-4I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(__builtin_inff()-4I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(198); } while (0);
  do { if (__builtin_cprojf(-__builtin_inff()+0I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-__builtin_inff()+0I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(199); if (__builtin_cproj(-__builtin_inff()+0I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-__builtin_inff()+0I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(199); if (__builtin_cprojl(-__builtin_inff()+0I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-__builtin_inff()+0I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(199); } while (0);
  do { if (__builtin_cprojf(-__builtin_inff()-0I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-__builtin_inff()-0I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(200); if (__builtin_cproj(-__builtin_inff()-0I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-__builtin_inff()-0I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(200); if (__builtin_cprojl(-__builtin_inff()-0I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-__builtin_inff()-0I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(200); } while (0);
  do { if (__builtin_cprojf(-__builtin_inff()+4I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-__builtin_inff()+4I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(201); if (__builtin_cproj(-__builtin_inff()+4I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-__builtin_inff()+4I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(201); if (__builtin_cprojl(-__builtin_inff()+4I) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-__builtin_inff()+4I)))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(201); } while (0);
  do { if (__builtin_cprojf(-__builtin_inff()-4I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-__builtin_inff()-4I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(202); if (__builtin_cproj(-__builtin_inff()-4I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-__builtin_inff()-4I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(202); if (__builtin_cprojl(-__builtin_inff()-4I) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-__builtin_inff()-4I)))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(202); } while (0);

  do { if (__builtin_cprojf(0+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(0+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(204); if (__builtin_cproj(0+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(0+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(204); if (__builtin_cprojl(0+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(0+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(204); } while (0);
  do { if (__builtin_cprojf(0-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(0-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(205); if (__builtin_cproj(0-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(0-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(205); if (__builtin_cprojl(0-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(0-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(205); } while (0);
  do { if (__builtin_cprojf(23+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(23+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(206); if (__builtin_cproj(23+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(23+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(206); if (__builtin_cprojl(23+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(23+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(206); } while (0);
  do { if (__builtin_cprojf(23-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(23-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(207); if (__builtin_cproj(23-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(23-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(207); if (__builtin_cprojl(23-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(23-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(207); } while (0);
  do { if (__builtin_cprojf(-0.F+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-0.F+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(208); if (__builtin_cproj(-0.F+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-0.F+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(208); if (__builtin_cprojl(-0.F+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-0.F+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(208); } while (0);
  do { if (__builtin_cprojf(-0.F-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-0.F-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(209); if (__builtin_cproj(-0.F-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-0.F-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(209); if (__builtin_cprojl(-0.F-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-0.F-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(209); } while (0);
  do { if (__builtin_cprojf(-23+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-23+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(210); if (__builtin_cproj(-23+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-23+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(210); if (__builtin_cprojl(-23+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-23+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(210); } while (0);
  do { if (__builtin_cprojf(-23-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-23-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(211); if (__builtin_cproj(-23-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-23-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(211); if (__builtin_cprojl(-23-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-23-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(211); } while (0);

  do { if (__builtin_cprojf(__builtin_inff()+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(__builtin_inff()+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(213); if (__builtin_cproj(__builtin_inff()+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(__builtin_inff()+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(213); if (__builtin_cprojl(__builtin_inff()+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(__builtin_inff()+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(213); } while (0);
  do { if (__builtin_cprojf(__builtin_inff()-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(__builtin_inff()-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(214); if (__builtin_cproj(__builtin_inff()-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(__builtin_inff()-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(214); if (__builtin_cprojl(__builtin_inff()-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(__builtin_inff()-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(214); } while (0);
  do { if (__builtin_cprojf(-__builtin_inff()+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-__builtin_inff()+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(215); if (__builtin_cproj(-__builtin_inff()+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-__builtin_inff()+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(215); if (__builtin_cprojl(-__builtin_inff()+1i*__builtin_inff()) != 0 +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-__builtin_inff()+1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0 +__builtin_inff()))))) link_error(215); } while (0);
  do { if (__builtin_cprojf(-__builtin_inff()-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-__builtin_inff()-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(216); if (__builtin_cproj(-__builtin_inff()-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(-__builtin_inff()-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(216); if (__builtin_cprojl(-__builtin_inff()-1i*__builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(-__builtin_inff()-1i*__builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(216); } while (0);

  do { if (__builtin_cprojf(0) != (0) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(0)))) != __builtin_copysignf((1),(__builtin_crealf((0))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(0)))) != __builtin_copysignf((1),(__builtin_cimagf((0))))))) link_error(218); } while (0);
  do { if (__builtin_cprojf(-0.F) != (-0.F) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(-0.F)))) != __builtin_copysignf((1),(__builtin_crealf((-0.F))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-0.F)))) != __builtin_copysignf((1),(__builtin_cimagf((-0.F))))))) link_error(219); } while (0);
  do { if (__builtin_cprojf(0-0.FI) != (0-0.FI) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(0-0.FI)))) != __builtin_copysignf((1),(__builtin_crealf((0-0.FI))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(0-0.FI)))) != __builtin_copysignf((1),(__builtin_cimagf((0-0.FI))))))) link_error(220); } while (0);
  do { if (__builtin_cprojf(-0.F-0.FI) != (-0.F-0.FI) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(-0.F-0.FI)))) != __builtin_copysignf((1),(__builtin_crealf((-0.F-0.FI))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-0.F-0.FI)))) != __builtin_copysignf((1),(__builtin_cimagf((-0.F-0.FI))))))) link_error(221); } while (0);

  do { if (__builtin_cprojf(22+3I) != (22+3I) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(22+3I)))) != __builtin_copysignf((1),(__builtin_crealf((22+3I))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(22+3I)))) != __builtin_copysignf((1),(__builtin_cimagf((22+3I))))))) link_error(223); } while (0);
  do { if (__builtin_cprojf(22-3I) != (22-3I) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(22-3I)))) != __builtin_copysignf((1),(__builtin_crealf((22-3I))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(22-3I)))) != __builtin_copysignf((1),(__builtin_cimagf((22-3I))))))) link_error(224); } while (0);
  do { if (__builtin_cprojf(-22+3I) != (-22+3I) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(-22+3I)))) != __builtin_copysignf((1),(__builtin_crealf((-22+3I))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-22+3I)))) != __builtin_copysignf((1),(__builtin_cimagf((-22+3I))))))) link_error(225); } while (0);
  do { if (__builtin_cprojf(-22-3I) != (-22-3I) || ((__builtin_copysignf((1),(__builtin_crealf(__builtin_cprojf(-22-3I)))) != __builtin_copysignf((1),(__builtin_crealf((-22-3I))))) || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(-22-3I)))) != __builtin_copysignf((1),(__builtin_cimagf((-22-3I))))))) link_error(226); } while (0);

  do { if (__builtin_cprojf(f+1i* __builtin_inff()) != 0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(f+1i* __builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0.FI +__builtin_inff()))))) link_error(228); if (__builtin_cproj(d+1i* __builtin_inff()) != 0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(d+1i* __builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0.FI +__builtin_inff()))))) link_error(228); if (__builtin_cprojl(ld+1i* __builtin_inff()) != 0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(ld+1i* __builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(0.FI +__builtin_inff()))))) link_error(228); } while (0);
  do { if (__builtin_cprojf(f+1i*- __builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojf(f+1i*- __builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(229); if (__builtin_cproj(d+1i*- __builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cproj(d+1i*- __builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(229); if (__builtin_cprojl(ld+1i*- __builtin_inff()) != -0.FI +__builtin_inff() || (__builtin_copysignf((1),(__builtin_cimagf(__builtin_cprojl(ld+1i*- __builtin_inff())))) != __builtin_copysignf((1),(__builtin_cimagf(-0.FI +__builtin_inff()))))) link_error(229); } while (0);
# 242 "builtin-cproj-1.c"
  return;
}

int main (void)
{
  return 0;
}
