# 1 "scalar-by-value-6_y.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "scalar-by-value-6_y.c"
# 1 "scalar-by-value-y.h" 1
extern void abort (void);
# 2 "scalar-by-value-6_y.c" 2

long double d = 1234.0L + 0x0.abcdp-70L;

_Complex long double cd = 234.0L + 0x0.abcp-70L + 567.0Li +0x0defp-70Li;


# 1 "scalar-by-value-6.c" 1
void longdouble_i_f0 (long double a, int b) { if (a != d || b != -987) abort (); } void longdouble_i_f1 (int z0, long double a, int b) { if (z0 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f2 (int z0, int z1, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f3 (int z0, int z1, int z2, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f4 (int z0, int z1, int z2, int z3, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f5 (int z0, int z1, int z2, int z3, int z4, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f6 (int z0, int z1, int z2, int z3, int z4, int z5, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f7 (int z0, int z1, int z2, int z3, int z4, int z5, int z6, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || z6 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f8 (int z0, int z1, int z2, int z3, int z4, int z5, int z6, int z7, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || z6 != (int) 0 || z7 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_f9 (int z0, int z1, int z2, int z3, int z4, int z5, int z6, int z7, int z8, long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || z6 != (int) 0 || z7 != (int) 0 || z8 != (int) 0 || a != d || b != -987) abort (); } void longdouble_i_fv (int n, ...) { __builtin_va_list ap; __builtin_va_start (ap, n); while (n-- != 0) if (__builtin_va_arg (ap, int) != (int) 0) abort (); if (__builtin_va_arg (ap, long double) != d) abort (); if (__builtin_va_arg (ap, int) != -987) abort (); __builtin_va_end (ap); }
void longdouble_d_f0 (long double a, double b) { if (a != d || b != -987.0) abort (); } void longdouble_d_f1 (double z0, long double a, double b) { if (z0 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f2 (double z0, double z1, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f3 (double z0, double z1, double z2, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f4 (double z0, double z1, double z2, double z3, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f5 (double z0, double z1, double z2, double z3, double z4, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f6 (double z0, double z1, double z2, double z3, double z4, double z5, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f7 (double z0, double z1, double z2, double z3, double z4, double z5, double z6, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || z6 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f8 (double z0, double z1, double z2, double z3, double z4, double z5, double z6, double z7, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || z6 != (double) 0 || z7 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_f9 (double z0, double z1, double z2, double z3, double z4, double z5, double z6, double z7, double z8, long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || z6 != (double) 0 || z7 != (double) 0 || z8 != (double) 0 || a != d || b != -987.0) abort (); } void longdouble_d_fv (int n, ...) { __builtin_va_list ap; __builtin_va_start (ap, n); while (n-- != 0) if (__builtin_va_arg (ap, double) != (double) 0) abort (); if (__builtin_va_arg (ap, long double) != d) abort (); if (__builtin_va_arg (ap, double) != -987.0) abort (); __builtin_va_end (ap); }

void complexlongdouble_i_f0 (_Complex long double a, int b) { if (a != cd || b != -987) abort (); } void complexlongdouble_i_f1 (int z0, _Complex long double a, int b) { if (z0 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f2 (int z0, int z1, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f3 (int z0, int z1, int z2, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f4 (int z0, int z1, int z2, int z3, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f5 (int z0, int z1, int z2, int z3, int z4, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f6 (int z0, int z1, int z2, int z3, int z4, int z5, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f7 (int z0, int z1, int z2, int z3, int z4, int z5, int z6, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || z6 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f8 (int z0, int z1, int z2, int z3, int z4, int z5, int z6, int z7, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || z6 != (int) 0 || z7 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_f9 (int z0, int z1, int z2, int z3, int z4, int z5, int z6, int z7, int z8, _Complex long double a, int b) { if (z0 != (int) 0 || z1 != (int) 0 || z2 != (int) 0 || z3 != (int) 0 || z4 != (int) 0 || z5 != (int) 0 || z6 != (int) 0 || z7 != (int) 0 || z8 != (int) 0 || a != cd || b != -987) abort (); } void complexlongdouble_i_fv (int n, ...) { __builtin_va_list ap; __builtin_va_start (ap, n); while (n-- != 0) if (__builtin_va_arg (ap, int) != (int) 0) abort (); if (__builtin_va_arg (ap, _Complex long double) != cd) abort (); if (__builtin_va_arg (ap, int) != -987) abort (); __builtin_va_end (ap); }
void complexlongdouble_d_f0 (_Complex long double a, double b) { if (a != cd || b != -987.0) abort (); } void complexlongdouble_d_f1 (double z0, _Complex long double a, double b) { if (z0 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f2 (double z0, double z1, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f3 (double z0, double z1, double z2, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f4 (double z0, double z1, double z2, double z3, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f5 (double z0, double z1, double z2, double z3, double z4, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f6 (double z0, double z1, double z2, double z3, double z4, double z5, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f7 (double z0, double z1, double z2, double z3, double z4, double z5, double z6, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || z6 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f8 (double z0, double z1, double z2, double z3, double z4, double z5, double z6, double z7, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || z6 != (double) 0 || z7 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_f9 (double z0, double z1, double z2, double z3, double z4, double z5, double z6, double z7, double z8, _Complex long double a, double b) { if (z0 != (double) 0 || z1 != (double) 0 || z2 != (double) 0 || z3 != (double) 0 || z4 != (double) 0 || z5 != (double) 0 || z6 != (double) 0 || z7 != (double) 0 || z8 != (double) 0 || a != cd || b != -987.0) abort (); } void complexlongdouble_d_fv (int n, ...) { __builtin_va_list ap; __builtin_va_start (ap, n); while (n-- != 0) if (__builtin_va_arg (ap, double) != (double) 0) abort (); if (__builtin_va_arg (ap, _Complex long double) != cd) abort (); if (__builtin_va_arg (ap, double) != -987.0) abort (); __builtin_va_end (ap); }
# 8 "scalar-by-value-6_y.c" 2
